Repository googleapis/nodejs-firestore-session, pull requests merged in 2019-06, with the labels that each got.

#36 chore: release 1.0.1
  CHANGELOG.md
  package.json
  samples/package.json
Labels: :rotating_light:, autorelease: pending, cla: yes, type: process

#39 docs: use compodoc to generate docs
  .compodocrc
  package.json
Labels: cla: yes

#40 feat(docs): move to new googleapis.dev URL
  .repo-metadata.json
  README.md
Labels: cla: yes

#41 chore: release 1.0.2
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes, type: process

#42 build: switch to GitHub magic proxy, for release-please
  .kokoro/continuous/node10/test.cfg
  .kokoro/test.sh
  synth.metadata
Labels: cla: yes

#43 fix(docs): link to reference docs section on googleapis.dev
  .jsdoc.js
  README.md
Labels: cla: yes

#44 chore: release 1.0.3
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes, type: process

#45 build: use config file for linkinator
  linkinator.config.json
  package.json
Labels: cla: yes
