Repository googleapis/nodejs-firestore-session, pull requests merged in 2019-05, with the labels that each got.

#12 chore: remove Node.js v6 CI
  .kokoro/continuous/node6/common.cfg
  .kokoro/continuous/node6/test.cfg
  .kokoro/presubmit/node6/common.cfg
  .kokoro/presubmit/node6/test.cfg
Labels: cla: yes

#13 build!: upgrade engines field to >=8.10.0
  package.json
Labels: cla: yes

#14 chore: do not run CI on grpc-js
  .kokoro/continuous/node10/system-test-grpcjs.cfg
  .kokoro/presubmit/node10/system-test-grpcjs.cfg
Labels: cla: yes

#19 build: allow Node 10 on presubmit to push to codecov
  .kokoro/presubmit/node10/test.cfg
  .kokoro/presubmit/node8/test.cfg
Labels: cla: yes

#17 build: patch Windows container, fixing Node 10
  .kokoro/test.bat
Labels: automerge, cla: yes

#18 build: allow Node 10 to push to codecov
  .kokoro/continuous/node10/test.cfg
  .kokoro/continuous/node8/test.cfg
Labels: automerge, cla: yes

#16 build: only pipe to codecov if tests run on Node 10
  .kokoro/lint.sh
  .kokoro/samples-test.sh
  .kokoro/test.sh
  synth.metadata
Labels: cla: yes, status: blocked

#7 feat: convert to TypeScript
  .gitignore
  package.json
  samples/quickstart.js
  src/index.js
  src/index.ts
  system-test/.eslintrc.yml
  system-test/session.js
  system-test/session.ts
  test/.eslintrc.yml
  test/test.ts
  tsconfig.json
  tslint.json
Labels: :rotating_light:, cla: yes, kokoro:force-run

#21 build: update kokoro configs
  .kokoro/continuous/node10/test.cfg
  .kokoro/continuous/node8/test.cfg
  .kokoro/lint.sh
  .kokoro/presubmit/node10/test.cfg
  .kokoro/presubmit/node8/test.cfg
  .kokoro/samples-test.sh
  .kokoro/test.bat
  .kokoro/test.sh
  .repo-metadata.json
  README.md
  synth.metadata
Labels: cla: yes, kokoro:force-ci

#20 build: use node-gcloud-ci project for CI testing
  .kokoro/pre-samples-test.sh
  .kokoro/pre-system-test.sh
  .kokoro/setup-vars.sh
Labels: cla: yes, kokoro:force-run

#22 build: do not run-script lint posttest
  .kokoro/continuous/node10/test.cfg
  .kokoro/continuous/node8/test.cfg
  .kokoro/lint.sh
  .kokoro/presubmit/node10/test.cfg
  .kokoro/presubmit/node8/test.cfg
  .kokoro/samples-test.sh
  .kokoro/test.bat
  .kokoro/test.sh
  .repo-metadata.json
  README.md
  package.json
  synth.metadata
Labels: cla: yes

#23 fix(docs): generate docs for compiled javascript
  .jsdoc.js
  README.md
  package.json
  synth.metadata
  synth.py
Labels: cla: yes

#25 build: fix Windows build and update coverage reporting
  .kokoro/continuous/node10/test.cfg
  .kokoro/continuous/node8/test.cfg
  .kokoro/lint.sh
  .kokoro/presubmit/node10/test.cfg
  .kokoro/presubmit/node8/test.cfg
  .kokoro/samples-test.sh
  .kokoro/test.bat
  .kokoro/test.sh
  synth.metadata
Labels: cla: yes

#28 chore: release 1.0.0
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes

#30 build: updated kokoro config for coverage and release-please
  .kokoro/continuous/node10/test.cfg
  .kokoro/release-candidate-issue.sh
  .kokoro/release-requested.sh
  .kokoro/release/publish.cfg
  .kokoro/release/release-candidate-issue.cfg
  .kokoro/release/release-requested.cfg
  .kokoro/test.sh
  synth.metadata
Labels: automerge, cla: yes

#32 chore: use published jsdoc-baseline package
  package.json
Labels: automerge, cla: yes, kokoro: force-run

#33 build: add configuration for automated doc deployment
  .kokoro/release/docs.cfg
  .kokoro/release/docs.sh
Labels: cla: yes

#35 build: ignore proto files in test coverage
  .nycrc
Labels: cla: yes

#37 fix: shell jobs were outputting too much information
  .kokoro/docs.sh
  .kokoro/lint.sh
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  .kokoro/trampoline.sh
Labels: cla: yes
