Repository googleapis/nodejs-firestore-session, pull requests merged in 2020-05, with the labels that each got.

#127 build: do not fail builds on codecov errors (#528)
  .github/workflows/ci.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#128 fix(sample): correctly pass firestoreStore constructor parameters
  samples/quickstart.js
Labels: cla: yes

#129 docs: modified quickstart sample
  README.md
  synth.metadata
Labels: cla: yes, context: none
