Repository googleapis/nodejs-firestore-session, pull requests merged in 2020-11, with the labels that each got.

#147 build(node): add KOKORO_BUILD_ARTIFACTS_SUBDIR to env
  .kokoro/trampoline_v2.sh
  synth.metadata
Labels: api: firestore, cla: yes, context: full

#149 fix(types): patch in express type removed SessionData
  package.json
  src/index.ts
  system-test/session.ts
  test/test.ts
Labels: api: firestore, cla: yes

#151 docs: spelling correction for "targetting"
  README.md
  synth.metadata
Labels: api: firestore, automerge, cla: yes, context: full
